AWSTemplateFormatVersion: "2010-09-09"
Description: Create a new CloudWatch Event rule and setup a new target to use existing SNS topic 

Metadata:

  Authors:
    Description: Max Charles (mcharles1682@gmail.com)

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Events
      Parameters:
        - RuleName
        - RuleState
        - RuleId

    ParameterLabels:
      RuleName:
        default: CloudWatch Events rule
      RuleState:
        default: CloudeWatch Events state 
      RuleId:
        default: CloudeWatch Events Id name         

Parameters:
  RuleName:
    Type: String
    Description: Name for the event rule.

  RuleState:
    Type: String
    Description: Turn on of off new event rule.
    Default: ENABLED
    AllowedValues:
    - DISABLED
    - ENABLED

  RuleId:
    Type: String
    Description: ID name for the target
    Default: HealhtEventTopic
    
Resources:
  HealthEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event rule to access all events from the Personal Health Dashboard
      EventPattern:
        source:
          - aws.health
      Name:
        Ref: RuleName
      RoleArn:
        Fn::ImportValue: !Sub HealthRole-RoleArn
      State: 
        Ref: RuleState
      Targets:
      - 
        Arn:
          Fn::ImportValue: !Sub HealthSNS-TopicArn
        Id:
          Ref: RuleId

Outputs:
  HealthEventRuleArn:
    Description: CloudWatch Events Rule Arn
    Value: !GetAtt HealthEventRule.Arn 
    Export:
      Name: HealthEvent-Arn
