AWSTemplateFormatVersion: "2010-09-09"
Description: Create new IAM role and IAM policy for CloudWatch Events

AWS::CloudFormation::Interface:
  ParameterGroups:
  - Label:
      default: IAM
    Parameters:
      - RoleName
      - PolicyName
  - Label:
      default: SNS
    Parameters:
      - TopicName
      - ReceipientEmailAddress
  - Label:
      default: Events
    Parameters:
      - RuleName
      - RuleState

  ParameterLabels:
    PolicyName:
      default: IAM policy name
    ReceipientEmailAddress:
      default: SNS subscription email addres
    RoleName:
      default: IAM role name
    RuleName:
      default: CloudWatch Events rule
    RuleState:
      default: CloudeWatch Events state
    TopicName:
      default: SNS topic name
      
Parameters:
  RoleName:
    Type: String
    Description: Name for the IAM Role to access Heath Dashboard alerts via CloudWatch Events.
    Default: HealthEventRole
  
  PolicyName:
    Type: String
    Description: Name for the IAM Policy to access Heath Dashboard alerts via CloudWatch Events.
    Default: HealthEventPolicy

  TopicName:
    Type: String
    Description: Name of the SNS Topic.
    Default: notifySDAWSENG

  RecipientEmailAddress:
    Type: String
    Description: Enter a valid email address for the subscription.

  RuleName:
    Type: String
    Description: Name for the event rule.

  RuleState:
    Type: String
    Description: Turn on of off new event rule.
    Default: ENABLED
    AllowedValues:
    - DISABLED
    - ENABLED        

Resources:
  RoleTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/mcharles350/aws-health-dashboard/blob/master/role.yaml
      Parameters:
        RoleName:
          Ref: RoleName
        PolicyName:
          Ref: PolicyName

  SNSTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/mcharles350/aws-health-dashboard/blob/master/sns.yaml
      Parameters:
        TopicName:
          Ref: TopicName
        RecipientEmailAddress:
          Ref: RecipientEmailAddress
        RoleName:
          GetAtt: [ RoleTemplate, Outputs.RoleName ]

  EventsTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/mcharles350/aws-health-dashboard/blob/master/events.yaml
      Parameters:
        RuleName:
          Ref: RuleName
        RuleState:
          Ref: RuleState
