AWSTemplateFormatVersion: "2010-09-09"
Description: Create new IAM role and IAM policy for CloudWatch Events

Metadata:

  Authors:
    Description: Max Charles (mcharles1682@gmail.com)

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: IAM
      Parameters:
        - RoleName
        - PolicyName
    - Label:
        default: SNS
      Parameters:
        - TopicName
        - RecipientEmailAddress
    - Label:
        default: Events
      Parameters:
        - RuleName
        - RuleState
        - RuleId

    ParameterLabels:
      PolicyName:
        default: IAM policy name
      RecipientEmailAddress:
        default: SNS subscription email addres
      RoleName:
        default: IAM role name
      RuleName:
        default: CloudWatch Events rule
      RuleState:
        default: CloudeWatch Events state
      TopicName:
        default: SNS topic name
      RuleId:
        default: CloudWatch Event Id name
      
Parameters:
  RoleName:
    Type: String
    Description: Name for the IAM Role to access Heath Dashboard alerts via CloudWatch Events.
    Default: HealthEventRole
  
  PolicyName:
    Type: String
    Description: Name for the IAM Policy to access Heath Dashboard alerts via CloudWatch Events.
    Default: HealthEventPolicy

  TopicName:
    Type: String
    Description: Name of the SNS Topic.
    Default: notifySDAWSENG

  RecipientEmailAddress:
    Type: String
    Description: Enter a valid email address for the subscription.
    ConstraintDescription: i.e. email@example.com

  RuleName:
    Type: String
    Description: Name for the event rule.

  RuleState:
    Type: String
    Description: Turn on of off new event rule.
    Default: ENABLED
    AllowedValues:
    - DISABLED
    - ENABLED  

  RuleId:
    Type: String
    Description: ID name for the target
    Default: HealhtEventRuled   

Resources:
  RoleTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/mcharles350/aws-health-dashboard/blob/master/role.yaml
      Parameters:
        RoleName:
          Ref: RoleName
        PolicyName:
          Ref: PolicyName

  SnsTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/mcharles350/aws-health-dashboard/blob/master/sns.yaml
      Parameters:
        TopicName:
          Ref: TopicName
        RecipientEmailAddress:
          Ref: RecipientEmailAddress
    DependsOn: RoleTemplate

  EventsTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/mcharles350/aws-health-dashboard/blob/master/events.yaml
      Parameters:
        RuleName:
          Ref: RuleName
        RuleState:
          Ref: RuleState
        RuleId:
          Ref: RuleId
    DependsOn: SnsTemplate
